package desafio.api.exception;

public class EmpresaNaoEncontradaException extends RuntimeException {
    public EmpresaNaoEncontradaException(Integer id) {
        super("A empresa de id " + id + " n√£o foi encontrada.");
    }
}
